name: Feature Request
description: Suggest an improvement or enhancement
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement

    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution

    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
